// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartConvert(arg1, arg2) {
  return window['go']['main']['App']['StartConvert'](arg1, arg2);
}
